### ISSUE TITLE
Make first release of CompendiumNG (2.1.1) preview 1 available

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#114]
We intend to make a first version of CompendiumNG available for download ASAP. This will allow the Compendium community to have a look at the great work Michal has been doing :-) In order to do this we:

**Have to:**
- Prepare an installer (issue #28)
- Prepare at least a _minimal_ website at compendiumNG.org (#119)

**Should (but don't have to):**
- Fix up the splash screen (#115)
- Remove all GUI elements related to functionality associated with fobs (#116)
- Finallize the review of user feedback systems in order to be ready for collecting suggestions (#108)

**It would be nice if we can:**
- Fix up the default content of newly created projects (issues #32 and #31)
- Clean up help system to remove all references to fobs related elements from it, that is media maps (#117)

**Comment by maiklos** [comment]
#28 - mostly finished, but also something new broken (see the comments there)

**Comment by maiklos** [comment]
#28 is closed now. 2 platform specific issues (#139 & #140) has been derived from #28 since they will not be fixed in 2.1.1 version but later.
#119 is implemented [CLOSED]
#115 [FIXED]
#116 - rolled over to another version
#117 - rolled over to another version
#108 - [CLOSED]
#32 - rolled over to another version
#31 - rolled over to another version

**Comment by SebastianBoell** [comment]
Just send out an email to the former development team at KMI and to the dev list. I will wait one day for some immediate feedback and then send out the announcement to the complete list.
