### ISSUE TITLE
"%" in the search function does not work as a symbol

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#123]
the percentage sign % when used in the Compendium 2.0 Beta 1 search function (Edit -> Seach) is not accepted as a symbol but as a place holder. For example, I use % often in Map and Note names, and upon searching for "95%" I get as a result everthing with 95 in the title what makes it very hard to find when numbers are often used in titles.

**Comment by maiklos** [comment]
a string (i.e. aaa) you put into the keyword field is passed to SQL  as "like '%aaa%'".
Therefore it is not only related only to % sign. If you have i.e. nodes labelled '01' and '10' and search for  "1" then both nodes are found. 

I am not sure what is preferred solution/behaviour for this. I assume both (exact match and wilcard match) are useful:
a) perform exact match always and allow for wild-cards (%,_) with possibility to escape them ?
b) perform exact search always and must escape wild-cards if you need them i.e.  use: \% if you need wildcard % ?
c) other ?

keywords are passed to the DB as they are including any special character like ', ", %.
Keyword field shouldn't allow this.

**Comment by mike223** [comment]
In my experience Compendium is already quite complicated to get started with for average users. 
Because of this I'd like to have the search as easy as possible: No special meaning of any characters.
The concept of escaping is as common to programmers as it is uncommon to the intended audience. 
I'd prefer to have a second search field (or a check box) for extended search: the string is directly evaluated by SQL. All special characters work as in "like '%aaa%bbb%'". And "aaa" would only find "aaa" not "baaa".

**Comment by maiklos** [comment]
solution: \* is wild-card character, comma "," is keyword separator, all other characters are not interpreted. 

i.e.
a\*   = all nodes starting with a
a_,b_ = all nodes starting with a or b
10% = all nodes with name "10%"

**Comment by mike223** [comment]
Sorry that I have to go after this (important) issue once more:
The comma is used instead of the decimal point in most european languages --> Losing the comma is worse than not being able to search for %.
I'd think that the OR functionality of the (standard) search is not so important: One can insert the first set of results (a_) into a map and the second set of nodes (b_) after. 
In fact I almost never needed the OR during the last years at all. 

For me the search is one of the most important parts of CompendiumNG. And it is going to need some more thoughts in the future. But for now I think it is enough to not decrease usability: 
Please do no use the comma as a special character. How about the pipe |   ?

**Comment by SebastianBoell** [comment]
Working with a lot of professional search services over the last few years I just like to note that or searches are usually implemented as the default if no additional operator is used. In the context of the request here this would probably be a single space ' '. So possibly space may be an even better choice than the pipe?

I am not sure if there are any technical constraints that would limit the possibility of using space or if space is used for implementing 'and' searches?
However, if an 'and' search is desired commonly the actual word AND is used as operator. Alternatively + can be used as operators in front of a search word to indicate that it needs to be present as part of a search (as done by google).

**Comment by maiklos** [comment]
the major problem with space is that it is the most common character in labels that have more than 1 word :-)

**Comment by SebastianBoell** [comment]
In this case we should consider have searching for phrases as an option in the future. Possibly using quotation marks to search for content "longer than one word".

I think for now this is fine, but we may want to look at the search as some point in the future (the feature suggesion map contains a number of suggestions). Just in general I think where possible it would be good to draw from widely used syntax.
