### ISSUE TITLE
Fit windows to content

### ISSUE THREAD

**Issue by mario-g** [CompendiumNG/CompendiumNG#127]
It would be useful for small maps to fit window dimensions to map content, if the right bound of the bounding box of the rightmost node and the bottom bound of the bounding box of the bottommost node define a width and a height which can be contained in the main window.

**Comment by SebastianBoell** [comment]
One important aspect of this is to consider the zoom level of a current window. Set this to 'minor' for now as we should have a general collection of ideas on how to improve working with multiple maps, switching between them, copy and pasting between maps, navigation etc. As a result of this our time may be better spend in reworking the current old school interface into something new rather than trying to fix issues within it (hope it makes sense what I am saying). Push this to version 2.8 rather than 'future' as it may be something to consider in the context of that release.

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/fit-windows-and-content/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
