### ISSUE TITLE
CompendiumNG.org identified as potentially maliscious

### ISSUE THREAD

**Issue by scribbly** [CompendiumNG/CompendiumNG#176]
MalwareBytes blocks compendiumng.org reporting 

```
IP-BLOCK    31.31.72.244 (Type: outgoing, Port: 51172, Process: chrome.exe)
```

**Comment by maiklos** [comment]
Thanks for reporting this. I did blacklist check on http://whatismyipaddress.com/blacklist-check and it seems this address wasn't reported except for one marginal blacklist. Also I hit the MalwareBytes discussion board on their site and found that they have even dedicated section (http://forums.malwarebytes.org/index.php?showforum=42) for reporting false positives with amazing 167 pages of reports (about 30 reports each page). 

Frankly if you care about this you can report it in their discussion board. Otherwise I would advice against using security software that has so many false positives.

**Comment by scribbly** [comment]
Thanks. First time MalwareBytes has ever complained about my browsing... but it's all part of your reputation, so I'm reporting it. :)

Local unblocking is available too :)
