### ISSUE TITLE
Image rollover does not render transparent areas

### ISSUE THREAD

**Issue by scribbly** [CompendiumNG/CompendiumNG#180]
If the attached image has transparent areas they are rendered as white in CNG.

**Comment by SebastianBoell** [comment]
Thanks for reporting this. I think we should look into this when we are reworking the CNG interface as there may be some major changes regarding the underlaying libraries that are currently used. Not sure though if it would always be good to maintain transparency. Indeed in some cases this would not really help in seeing the image properly on a crouded map as background.

**Comment by scribbly** [comment]
Agreed. Maybe having a keyboard override to toggle transparency, such as ALT? And a toggle on the Contents tab to set the default (transparency on | off)?

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/image-rollover-should-render-transparent-areas/> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
