### ISSUE TITLE
application vs user data

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#2]
there should be clear separation of user content (user configuration, data) from application content binary code, icons etc.

proposal:

user application settings should be stored in user home directory  .compendium on unix like systems compendium-settings on windows like

user database and related data should be all stored in designated directory selected by user - somewhe in user home 
defaults to compendium-data on linux/win/mac

compendium during first run/installation should create these user directories and place default configuration there.

then it should never overwrite it - only new version of comependium can add  new parameter should add to it

compendium must never fail on loading parameter it doesn't understand but must warn about it

configuration load procedure

1) application default configuration is loaded
2) user setting (if available) is loaded over application default

this way any user setting take precedence over default settings.

**Comment by SebastianBoell** [comment]
Importantly, currently settings for compendium are stored in multiple locations. Also some can be adjusted through the interface, others only by directly changing entries in files. I guess it would be good to collect a short list of what settings can be adjusted and where. Based on this we could try to centralize these settings.

About storage of settings outside of the compendium directory I can only see one problem if Compendium is run through a cloud service on multiple machines (and OS) or from USB. For these arrangements storage of settings together with content may be more appropriate. This would also allow to change some settings when a project is loaded, hence the ability to have multiple appearances of Compendium for different projects (and potentially for different usage templates). For example in one project the 'tags' sidebar and the links menu should appear while in another project it should not.

I suggest to keep storing settings with compendium and close this issue. In addition I also suggest to open a new issue on compiling a list of all possibly settings in Compendium and storage location of them.

**Comment by maiklos** [comment]
separation of user/application/resources/data done via installer. Installer will create separate directories (as preconfigured). Locations can be also changed by user. The only hardcoded locatio is for user setting directory
which is in his/her home directory in .compendiumng. The rest is configurable via USER_HOME/.compendiumng/main.properties.

**Comment by SebastianBoell** [comment]
I saw the details for the installer on the [wiki](https://github.com/CompendiumNG/CompendiumNG/wiki/CompendiumNG-installer). Certainly a clear separation of application, data, backups and exports is highly derirable. I especially like that now data is clearly locateable for users which often was an issue on the user mailing list as users had troubles with finding their data for backup, and restore purposes.

As part of this rework a new installation currently creates four directories inside a users home directory. I just wonder if it would be possible to do them all in side a single CompendiumNG directory? For structure I suggest it may be good to only have one 'CompendiumNG' directory and within it four subdirectories for: application, data, backups, export.
-OR- if the application should go somewhere else it may be good to have a base directory for content that in it has: 'infbase' (collecting all information bases/data), 'export', 'backup' and maybe in the future one for 'templates' that can be auto-scanned by CNG so that templates may even be installed by copying them there. Of course I agree ideally backups should be on a separate drive, but for some users having all content in a singel 'content' directory may be the easiest option.

This may also avoid problems for users running CNG through a cloud or USB as the application and data can be referring to each other using only relative links.

**Comment by maiklos** [comment]
closing. Running CNG from flash disk or in cloud will be addressed in separate issue (#131)

**Comment by SebastianBoell** [comment]
My the way great work with this separatio of data, setting and application files!
