### ISSUE TITLE
Feature: Ctrl+MouseWheel zoom could be centered on where mouse pointer is :)

### ISSUE THREAD

**Issue by ghost** [CompendiumNG/CompendiumNG#222]
This would be great feel if zooming in via Ctrl+mousewheel  would consider the center to be where the mouse pointer is in the window, instead of top left corner of window.
Please consider it. Thank you.

EDIT: or maybe Ctrl+Alt+mousewheel would do this, and Ctrl+mousewheel would do what it currently does ?

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/mousewheel-zoom-should-be-centered-on-where-mouse-pointer-is/"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
