### ISSUE TITLE
Double absolute reference in map background

### ISSUE THREAD

**Issue by PhDyellow** [CompendiumNG/CompendiumNG#223]
windows 7
compendium 2.1.5 and 2.1.4
java version 7 update 60

This might be related to issue #217 
Steps:
create a new map node
edit the contents of the map node
add a background image using the browse button
select a file outside the compendium directory
select ok or open the map

result:

<pre>
Error:Exception: (ProjectCompendiumFrame.addViewToDesktop)
Cannot instantiate MapView Frame 
Illegal char <:> at index 49: C:\Users\username\Documents\compendiumNG\\images\C:\Users\username\Documents\temp_pdf\detect_cells.png
</pre>

The absolute path generated by browse is being concatenated with another absolute path. If I enter a relative path such as ....\temp_pdf\detect_cells.png it behaves properly.

**Comment by maiklos** [comment]
when the background image file is selected, then the path is store as absolute path.
While the map is being opened then the path to the image directory is concatenated with absolute path. On windows it throws and exception, on Linux it fails silently. On both platforms it doesn't display the background image. 

The problem here is that background image should be treated in the same way a LinkedFiles - it should be copied to the image directory or left where it is depending on user settings.

I made fix that will ensure that background image is loaded always from as it were absolute path.
This will work unless you move your whole db to another directory in which case you have to correct all background images paths.

This workaround is implemented in 8991b4e4a5ffac82d0a482f7f762fbd3aca519af

In future we should really treat background images as any other image/resource that is added to the map (i.e. as LinkedFiles).

**Comment by maiklos** [comment]
closing issue
