### ISSUE TITLE
Improvements for Search Window

### ISSUE THREAD

**Issue by mcomp** [CompendiumNG/CompendiumNG#254]
The search function should be improved a bit:

Firstly, the search window shoudn't be fixed to the front, because this prevents from working in or simply looking into other maps after the search window has been opened.

Also, having a "Search and/or Replace" function would be useful to have.

With the Search results, it would make more sense to have a certain node/map opened directly via double-click, instead of having the "Open" button. Now, double-click on a node/map in the search result list only opens the content window. Intuitively, it would be better to use double-click for "open" and, for example, have the Contents reached by right-click --> Context Menu --> Contents (like in lists).

(Compendium Version 2.0 beta 1 and 2.1.4 run on Linux Mint 13 Xfce and java version "1.7.0_65")

**Comment by maiklos** [comment]
:warning: this issue tracker is for CompendiumNG not for Compendium. But since the find dialog is pretty much the same including behavior we can accept it as CompendiumNG issue. Just please be aware that any solution will only apply to CompendiumNG and not to Compendium.

<strong>I see tree requests/issues here:</strong>
- :one:  to make search dialog non-modal. 
  - I pretty much agree so I will look into it
- :two: request to have **replace** feature added to the search dialog
- :three: request to open the node on a map when node is clicked in find result list
  - :two: :heavy_plus_sign:  :three: would be more complicated so it should go to FSP first. 

conclusion: this ticket (#254) will be further used only to discuss :one:

**Comment by maiklos** [comment]
:one: :ok: fixed in a0ffc6ad26d499e61e675dc181b3534b6fd4cd68
:two: :arrow_right:  http://www.compendiumng.org/questions/add-replace-function-to-the-search-dialog/
:three:  :arrow_right:  http://www.compendiumng.org/questions/improve-search-results-window/
