### ISSUE TITLE
"Search Google" data compromise

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#41]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=974

It is easy to start the "Search Google" function by accident. This would send a
node title which might contain sensitive information over the internet. 
The easiest solution would be to have an option to deactivate the search. But
it would be even more useful if users could specify a custom command to run.

**Comment by SebastianBoell** [comment]
Trying this on Linux I had to select an application after selecting the 'search google' function. Selecting iceweasel worked fine. I guess this may be a candidate for something to include in a centralized settings menu.

**Comment by maiklos** [comment]
Compendium can't decide on it's own if some data are or are not sensitive unless they are tagged somehow.
this is related to tagging.

There should be options in setting (probably on map level and compendium installation)
- sensitive data handling level:
  - closed: search on internet is disabled
  - secure: allow to search only for white-listed tags
  - normal: "secure" + don't search for blacklisted and ask/user review for the rest. Once the user approves  untagged  node for internet search it will be auto-tagged as white-listed (or black-listed if search is not approved)
  - relaxed: only blacklisted is not searched the other is silently searched
  - open: anything is searched. tags are ignored completely and any search is allow
- sensitive data tagging:
  - blacklisted tag: secure,password,secret,pass (i.e.)
  - whitelisted tags: public (i.e)

in M1 I would like have "data review" implemented so user can see what will be sent to the internet.
This of course has a shortcoming that user has to do one more click. I wonder if this "search in google" feature
is used extensively among users. 

Google has also https://google.com if simple eavesdropping is the main concern

if Google itself is the concern than it should be up to the user to select search provider.

so we have a new enhancement request: "allow to use alternative internet search provider"
there should be setting to set preferred search provider with customizing the search URL.

tag based security should go for later milestone.

**Comment by mike223** [comment]
I'd vote to increase the severity level of this user interface bug. Anybody who uses Compendium to work on Personally Identifiable or secret information might even face legal consequences. Because the information is not properly protected against accidentally sending it to Google. 
I almost never use the Google search on node titles. One reason is the frequent use of transclusion in Compendium. If nodes are to be used at several places it is necessary to have longer and more descriptive node titles. Such titles are less usable for a Google search. 
Please give us a means to deactivate the search. 

Mike and his 15k+ nodes

**Comment by maiklos** [comment]
google search disable is implemented in 820bb (branch M1)

google search is disabled by default now.

if user want to use it must be confgured first. create your_home_directory/.compendiumnng/main.cfg text file

## and add following lines:

```
internet.search.allowed=true
internet.search.url=https://www.google.com/search?q=
```

---

**Comment by SebastianBoell** [comment]
Great job and really quick reaction! 
You even already layed the foundation for supporting more and different types of searches in the future. I already saw a request for this bubbling up in the feature suggestions.

**Comment by mike223** [comment]
Thanks. For me as the original reporter this issue is resolved. 

Nevertheless I'd still like the importance level to be increased to red: I think it was a danger at least as serious as a crashing application. According to the definitions in the wiki 
( https://github.com/CompendiumNG/CompendiumNG/wiki/Issue-tracking-system )
I'd qualify this and similiar issues as bugs. Seems to be more near to "faulty behaviour" than to a need for "enhancements of CompendiumsNG's capabilities" if the software does something potentially dangerous to the user. 
Proper tags and assignments even for resolved issues could be valuable if an analysis of bug fixing activities is to be done later on. 

Good to know that you value user feedback. We will try to do our job of writing new reports as fast.

**Comment by maiklos** [comment]
ok, agree. Sebastian, could please take my comment above as a "feature request" ?

I will close this as critical to match original bug report.
Mike, thanks for your suggestion, it really make more sense this way.

maiklos

**Comment by SebastianBoell** [comment]
Ok marked this idea as new issue #110 for now. Will also include it into the features DB. (reviewing the content from our issue system here will be the last step as part or #106.
