### ISSUE TITLE
connecting two elements

### ISSUE THREAD

**Issue by maiklos** [CompendiumNG/CompendiumNG#6]
imported from previous githube issue tracker:

when I make connection between two elements the connection is created however it is not possible to connect them again with another connection.

i.e.   A -> B  and B -> A

I see no reason why it shouldn't be possible to have multiple connections so it is probably a bug not enhancement request :-)

**Comment by SebastianBoell** [comment]
I like the idea of having multiple paths between nodes. If I understood you right you are thinking about two paths, a to b and b to a. Of course then the question is why not have more than that? (multiple linke, e.g. for different aspects, some with thick lines, other with thin ones, etc.)
I guess the question is when will it become messy in the visualization? In many cases it may be better to simply have some nodes in between nodes instead. This may be something to be played around in order to find a good way of dealing with multiple paths between two nodes. In particular I think about visualization and curves in order to stagger the paths in a good way. Because of these issues it is possibly something to work on for M4; also it may require some adjustment of the data storage for links as part of M3. For now I suggest to push to the future release milestone?

**Comment by maiklos** [comment]
from my point of view  relationship for nodes should be    1:*. which means no limits on number of relationship between nodes. 

regarding visualization: there should be filters for hiding some nodes/edges (based on criteria)
I would like to introduce concept of model vs view. You can have 2 views that display different aspects (nodes,edges) from a model based on what interests you.

i.e. you have argument map and you would have 2 views one with main ideas only and the second with arguments without con/pro only. Both view have different purpose but they are visualization of the same model

**Comment by SebastianBoell** [comment]
I like both issues:

a) The ability to show/hide nodes or links. I guess we could implement this using tags? Tags could then be successively switched on/off to create different views.

b) Having multiple links between a set of nodes. Here visualisation through different sets of staggered curved lines is important so that it visually clear that two issues are related in multiple ways.

**Comment by maiklos** [comment]
ad a) it make sense to have filtering based also on tags (not only). There are attributes that are implicit properties of a node (like modification date/time) which shouldn't be tags. However we might want to create view that displays only nodes modified by "me"

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/multiple-links-between-two-nodes/">Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
