### ISSUE TITLE
Welcome screen should always be displayed when no project is opened.

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#80]
Also the welcome screen may continue a button opening existing projects 'load project' (or to use the new terminology 'load information base'. :)

**Comment by maiklos** [comment]
1) when admin database doesn't exist you will get welcome page
2) when there is no registered project in the admin db then you will get welcome page
3) when there is at least one project registered you will get list of project to choose from 

from welcome screen you can go to application (where you can manage projects, create new project, but not "open" because there is nothing to be opened)

IMO another button for opening a project (while you got welcome screen exactly because there is no project to be opened) doesn't make sense. Current usage scenarios are IMO completely covered by current behavior.

I tested this behaviour in b40b6

**Comment by SebastianBoell** [comment]
I think this issue was created when there still was a 'welcome screen' button in the 'help' menu. Since we have removed this I agree that there will be no project to open, hence no need for such a button.
