### ISSUE TITLE
Refresh View doesn't work for local MySQL database

### ISSUE THREAD

**Issue by SebastianBoell** [CompendiumNG/CompendiumNG#83]
http://compendium.open.ac.uk/bugzilla/show_bug.cgi?id=915

Mike 2010-07-28 22:05:48 BST

The "Refresh View" functionality seems to be deactivated for MySQL databases
accessed over the loopback interface. 

This behavior prevents the following use cases for "Refresh view":
- remote MySQL database secured by SSH (an easy way to use Compendium for group
  working over the internet)
- local MySQL database that is also accessible by remote hosts
- local MySQL database with external programs changing data (Compendium as a
  viewer for external data)

In certain cases it might be possible to circumvent this issue by accessing the
MySQL database using the LAN or WAN IP. But this needs a more complicated (and
dangerous) firewall setup. 
On the other hand it seems that there is no danger in activating the "Refresh
View" button whenever a MySQL database is connected.

**Comment by maiklos** [comment]
This might look like an obstacle to collaboration over shared database but in fact even if it worked Compendium still doesn't support concurrent collaboration features. 

I didn't see stated anywhere that C. supports concurrent collaboration over internet.
The fact that it supports data stored in database server doesn't automatically mean that it allows concurrent access by several users. I am considering this as new feature that will be handled in M5.

**Comment by mike223** [comment]
I forgot one use case: Several users on one terminal server with a shared MySQL database. 

This basic concurrent collaboration seems to be part of Compendium from at least 1.5.2. 
From the 2.0 Beta 1 help on Group Working: 
"In order to support people wishing to take advantage of MySQL as a shared Compendium database, we have added some support into Compendium for group working."
"This icon allows you to reload the locally viewed data from the database when you press it. It will only be available when you are connected to a remote MySQL database."

So the feature was implemented already. The only problem is that it is deactivated for no good reason for the most important host:   localhost

**Comment by mike223** [comment]
Workaround:
Give 127.0.0.1 an additional hostname: e.g. by adding the line   "127.0.0.1       another-localhost"
into /etc/hosts on Linux.
Compendium does not check for the IP but for the hostname "localhost".
When you connect to MySQL-database at another-localhost you get the connection to the local computer as usual but Compendium activates the "Refresh View" functionality. 

Could work on Windows XP too: The file to look for is    c:\WINDOWS\system32\drivers\etc\hosts

**Comment by SebastianBoell** [comment]
This feature suggestion is now on the <a href="http://www.compendiumng.org/questions/improve-mysql-db-connection-setup/#answer-715"> Feature Suggestion Page (FSP)</a>. Please go there to vote for it and for leaving your comments. We will re-open the issue here when the suggestion is well supported on the FSP.
